project_id = "meisahpkysqibnjyvubh"

[functions.subblock-ai]
verify_jwt = false

[functions.lottiefiles-search]
verify_jwt = false

[functions.lottiefiles-ai-suggest]
verify_jwt = false

[functions.generate-course-banners]
verify_jwt = false

[functions.generate-course-metadata]
verify_jwt = false

[functions.update-course-banners]
verify_jwt = false

[functions.refine-course]
verify_jwt = false

[functions.translate-course]
verify_jwt = false